# ============================================================
# Minimal clean Jekyll config for Centrarium theme
# ============================================================

title: Penn Shen Lab
email: Li.Shen@pennmedicine.upenn.edu
description: Documentation for the Penn Shen Lab
url: "https://pennshenlab.github.io"
github_username:  PennShenLab

# Load Centrarium as a remote theme (GitHub-friendly)
remote_theme: bencentra/centrarium

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

# No posts yetâ€”clean site
collections:
  posts:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - .gitignore
  - .gitmodules